version: '3.9'

volumes:
    pgdata:

services:
    db:
        image: postgres:latest
        container_name: postgres_db
        restart: always
        env_file: ../.env_dev
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

